pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r assets/* public/ || true
    - cp -r module/* public/ || true
    - cp _sidebar.md public/
    - cp fullProcessDescription.html public/
    - cp fullProcessDescription.md public/
    - cp homePage.md public/
    - cp index.html public/
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - shared' > .gitlab-ci.yml